New ParametersTest file
Super-Visions/itop-data-collector-base pull request #3
Opened 2023-06-20 07:26 UTC by piRGoif

Adding a more atomic test of the PR Combodo/itop-data-collector-base#9
See https://github.com/Combodo/itop-data-collector-base/pull/9#issuecomment-1590803158

2023-06-20 07:32 UTC, Hipska requested changes

2023-06-20 07:32 UTC, Hipska commented on test/ParametersTest.php
> +@define('APPROOT', dirname(__FILE__, 2).'/');
What about
```suggestion
@define('APPROOT', dirname(__DIR__).'/');
```

2023-07-31 08:58 UTC, Hipska reviewed
https://github.com/Combodo/itop-data-collector-base/pull/9#issuecomment-1543679526
> The only thing I'm having a problem with is that your test requires the xml to be exactly the same. While an xml with elements in a different order would result in the same configuration as expected, but the test would fail. Both xml and php arrays don't have a guaranteed fixed ordering of elements.
> 
> I would be fine if the test would say for example it should contain `<broken_param>(&amp;(objectClass=person)(mail=*))</broken_param>`.

2023-07-31 09:06 UTC, piRGoif commented
I'm not sure I understand your comment, as the tests uses assertStringContainsString() ?

2023-07-31 09:17 UTC, Hipska commented
This test does, but the one I was referring to in my original comment (test/UtilsTest.php) isn't.

Also, the second test here for the arrays might sometimes fail, but I guess it is fine for now.

2023-07-31 09:17 UTC, merged

2023-07-31 15:01 UTC, piRGoif commented
Ok, thanks for the merge !